server:
  port: 8081


api:
  url: https://exercisedb.p.rapidapi.com/exercises
  key: ${API_KEY}
  host: exercisedb.p.rapidapi.com


keycloak:
  cors: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            serverUrl: http://localhost:8080
            client-id: workout-app
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/WorkoutApp
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/WorkoutApp
          jwk-set-uri: http://localhost:8080/realms/WorkoutApp/protocol/openid-connect/certs
